name: Deploy to S3 Bucket

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build the app
        run: ./mvnw clean package -DskipTests

      - name: Zip build artifact
        run: |
          cp target/*.jar app.jar
          zip springboot-greeting-app.zip app.jar

      - name: Upload ZIP to S3
        run: |
          aws s3 cp springboot-greeting-app.zip s3://${{ secrets.AWS_S3_BUCKET }}/springboot-greeting-app.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Create new Elastic Beanstalk app version
        run: |
            aws elasticbeanstalk create-application-version \
              --application-name "${{ secrets.EB_APP_NAME }}" \
              --version-label "${{ github.sha }}" \
              --source-bundle S3Bucket="${{ secrets.AWS_S3_BUCKET }}",S3Key=springboot-greeting-app.zip \
              --region "${{ secrets.AWS_REGION }}"
        env:
            EB_APP_NAME: ${{ secrets.EB_APP_NAME }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Update EB environment to new version
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name "${{ secrets.EB_ENV_NAME }}" \
            --application-name "${{ secrets.EB_APP_NAME }}" \
            --version-label "${{ github.sha }}" \
            --region "${{ secrets.AWS_REGION }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}